# Generated by Django 6.1 on 2026-10-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_post_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
